env:
  es2021: true
  node: true
  screeps/screeps: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
  sourceTYpe: module
rules:
  require-jsdoc: 0
  "@typescript-eslint/no-unused-vars":
  - warn
  - argsIgnorePattern: "^_"
    varsIgnorePattern: "^_"
    caughtErrorsIgnorePattern: "^_"
  #max-len:
  #  - warn
  #  - code: 120
  indent: off
  no-cond-assign: off
  no-bad-map-access/no-bad-map-access: error
plugins:
  - screeps
  - '@typescript-eslint'
  - 'no-bad-map-access'
root: true
