env:
  es2021: true
  node: true
  screeps/screeps: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
  sourceTYpe: module
rules:
  require-jsdoc: 0
  '@typescript-eslint/no-unnecessary-condition':
  - off
  '@typescript-eslint/no-unused-vars':
  - error
  - argsIgnorePattern: "^_"
    varsIgnorePattern: "^_"
    caughtErrorsIgnorePattern: "^_"
  no-unused-vars:
  - off
  #max-len:
  #  - warn
  #  - code: 120
  no-cond-assign: off
  no-bad-map-access/no-bad-map-access: error
  '@typescript-eslint/prefer-nullish-coalescing': warn
  '@typescript-eslint/dot-notation': off
plugins:
  - screeps
  - '@typescript-eslint'
  - 'no-bad-map-access'
root: true
