env:
  es2021: true
  node: true
  screeps/screeps: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
  sourceTYpe: module
rules:
  require-jsdoc: 0
  max-len:
    - warn
    - code: 120
  indent: off
  no-cond-assign: off
  bad-map-access/bad-map-access: error
plugins:
  - screeps
  - '@typescript-eslint'
  - 'bad-map-access'
root: true
