env:
  es2021: true
  node: true
  screeps/screeps: true
extends:
# - google
# - eslint:recommended
 - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  require-jsdoc: 0
  max-len:
    - warn
    - code: 120
  indent: off
plugins:
  - screeps
  - '@typescript-eslint'
root: true
